name: BuildFirmware

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    tags:
      - "v*"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      # Runs a set of commands using the runners shell
      - name: Set up west and project
        run: |
          sudo apt install --no-install-recommends git cmake ninja-build gperf \
          ccache dfu-util device-tree-compiler wget \
          python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
          make gcc gcc-multilib g++-multilib libsdl2-dev
          pip3 install --user -U west
          west init ~/zephyrproject --mr v2.5.0
          cd ~
          wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.12.4/zephyr-sdk-0.12.4-x86_64-linux-setup.run
          chmod +x zephyr-sdk-0.12.4-x86_64-linux-setup.run
          ./zephyr-sdk-0.12.4-x86_64-linux-setup.run -- -d ~/zephyr-sdk-0.12.4
          cd ~/zephyrproject
          west update
          west zephyr-export
          pip3 install --user -r ~/zephyrproject/zephyr/scripts/requirements.txt
          echo "${{secrets.MCUBOOT_KEY}}" > bootloader/mcuboot/root-ec-p256.pem
          

      - name: Build FW
        run: |
          cd ~/zephyrproject
          west build $GITHUB_WORKSPACE -b particle_xenon --pristine -- -D OVERLAY_CONFIG=overlay-usb-nrf-br.conf
          cp build/zephyr/zephyr.signed.hex /tmp/ncp-particle_xenon.hex
          west build $GITHUB_WORKSPACE -b e73minimal_nrf52840 --pristine
          cp build/zephyr/zephyr.signed.hex /tmp/ncp-e73minimal_nrf52840.hex
          west build $GITHUB_WORKSPACE -b particle_xenon --pristine -- -D OVERLAY_CONFIG="overlay-usb-nrf-br.conf;overlay-rcp.conf"
          cp build/zephyr/zephyr.signed.hex /tmp/rcp-particle_xenon.hex
          west build $GITHUB_WORKSPACE -b e73minimal_nrf52840 --pristine -- -D OVERLAY_CONFIG="overlay-rcp.conf"
          cp build/zephyr/zephyr.signed.hex /tmp/rcp-e73minimal_nrf52840.hex
          west build $GITHUB_WORKSPACE -b particle_xenon --pristine -- -D OVERLAY_CONFIG=overlay-usb-nrf-br.conf;overlay-no-bootloader.conf"
          cp build/zephyr/zephyr.hex /tmp/ncp-particle_xenon_no_bootloader.hex
          west build $GITHUB_WORKSPACE -b e73minimal_nrf52840 --pristine -- -D OVERLAY_CONFIG="overlay-no-bootloader.conf"
          cp build/zephyr/zephyr.hex /tmp/ncp-e73minimal_nrf52840_no_bootloader.hex
          west build $GITHUB_WORKSPACE -b particle_xenon --pristine -- -D OVERLAY_CONFIG="overlay-usb-nrf-br.conf;overlay-rcp.conf;overlay-no-bootloader.conf"
          cp build/zephyr/zephyr.hex /tmp/rcp-particle_xenon_no_bootloader.hex
          west build $GITHUB_WORKSPACE -b e73minimal_nrf52840 --pristine -- -D OVERLAY_CONFIG="overlay-rcp.conf;overlay-no-bootloader.conf"
          cp build/zephyr/zephyr.hex /tmp/rcp-e73minimal_nrf52840_no_bootloader.hex
          

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            /tmp/ncp-particle_xenon.hex
            /tmp/ncp-e73minimal_nrf52840.hex
            /tmp/rcp-particle_xenon.hex
            /tmp/rcp-e73minimal_nrf52840.hex
            /tmp/ncp-particle_xenon_no_bootloader.hex
            /tmp/ncp-e73minimal_nrf52840_no_bootloader.hex
            /tmp/rcp-particle_xenon_no_bootloader.hex
            /tmp/rcp-e73minimal_nrf52840_no_bootloader.hex
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

